### 
# 로그인
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"soo@naver.com",
    "password":"123445677"
} 

###
# 로그아웃
GET http://localhost:3000/api/auth/logout
