###
# 상품 생성
POST http://localhost:3000/api/products/new
Content-Type: application/json

{
    "productName":"감a",
    "price": 5000,
    "productContent": "수박 비싸유"
} 
 
###
# 상품 목록 조회
GET http://localhost:3000/api/products

###
# 상품 상세 조회
GET http://localhost:3000/api/products/6

###
# 상품 수정
PUT http://localhost:3000/api/products/7
Content-Type: application/json

{
    "productName":"감",
    "status":"SOLD_OUT",
    "price": 3000,
    "productContent": "다팔림"
}  

###
# 상품 삭제
DELETE  http://localhost:3000/api/products/8
