###
# 회원가입
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "email":"soo5@naver.com",
    "password":"1234567",
    "username":"tndud5",
    "confirmPassword": "1234567"
} 
 

###
# 사용자 정보조회
GET http://localhost:3000/api/users/1
 